package org.fao.geonet.datahub;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import org.springframework.core.io.ClassPathResource;

// Generated by ChatGPT
public class FileUtils {
    private static final Path TEMP_DIR;

    static {
        try {
            TEMP_DIR = Files.createTempDirectory("plugin_cache");
            TEMP_DIR.toFile().deleteOnExit(); // Ensure temp directory is cleaned up
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public static boolean fileExistsInJar(String relativePath) {
        ClassPathResource resource = new ClassPathResource(relativePath);
        return resource.isReadable();
    }

    public static File getFileFromJar(String relativePath) throws IOException {
        Path tempFile = TEMP_DIR.resolve(relativePath.substring(1));
        if (Files.exists(TEMP_DIR.resolve(relativePath))) {
            return tempFile.toFile();
        }

        if (!FileUtils.fileExistsInJar(relativePath)) {
            throw new IOException("File not found: " + relativePath);
        }

        ClassPathResource resource = new ClassPathResource(relativePath);

        Files.createDirectories(tempFile.getParent());

        // Copy resource contents to temp file
        try (InputStream inputStream = resource.getInputStream();
             FileOutputStream outputStream = new FileOutputStream(tempFile.toFile())) {
            inputStream.transferTo(outputStream);
        }

        tempFile.toFile().deleteOnExit(); // Mark for deletion on JVM exit
        return tempFile.toFile();
    }

    public static String readFromInputStream(InputStream inputStream)
            throws IOException {
        StringBuilder resultStringBuilder = new StringBuilder();
        try (BufferedReader br
                     = new BufferedReader(new InputStreamReader(inputStream))) {
            String line;
            while ((line = br.readLine()) != null) {
                resultStringBuilder.append(line).append("\n");
            }
        }
        return resultStringBuilder.toString();
    }
}
