UPDATE metadata SET data = replace(data,'<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:LocalName>%';

UPDATE metadata SET data = replace(data,'<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:LocalName>%';

UPDATE metadata SET data = replace(data,'<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:LocalName>%';

UPDATE metadata SET data = replace(data, '<gco:Boolean>0</gco:Boolean>', '<gco:Boolean>false</gco:Boolean>') WHERE data LIKE '%<gco:Boolean>0</gco:Boolean>%';
UPDATE metadata SET data = regexp_replace(data,'<mdq:pass>[[:space:]]*<gco:Boolean />[[:space:]]*</mdq:pass>','<mdq:pass gco:nilReason="unknown"/>','g');
UPDATE metadata SET data = regexp_replace(data,'<mdq:pass>[[:space:]]*<gco:Boolean><gco:Boolean/>[[:space:]]*</mdq:pass>','<mdq:pass gco:nilReason="unknown"/>','g');
UPDATE metadata SET data = replace(data, '<mdq:pass gco:nilReason=""/>', '<mdq:pass gco:nilReason="unknown"/>') WHERE data LIKE '%<mdq:pass gco:nilReason=""/>%';
UPDATE metadata SET data = replace(data, '<mdq:pass gco:nilReason="missing"/>', '<mdq:pass gco:nilReason="unknown"/>') WHERE data LIKE '%<mdq:pass gco:nilReason="missing"/>%';


UPDATE metadata SET data = replace(data, '<gcx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/4326 WGS 1984">EPSG:4326EPSG:4326</gcx:Anchor>', '<gcx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/4326">EPSG:4326</gcx:Anchor>') WHERE data LIKE '%<gcx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/4326 WGS 1984">EPSG:4326EPSG:4326</gcx:Anchor>%';
UPDATE metadata SET data = replace(data, '<gco:CharacterString>WGS 84 (EPSG:4326) WGS 84 (EPSG:4326)</gco:CharacterString>', '<gco:CharacterString>WGS 84 (EPSG:4326)</gco:CharacterString>') WHERE data LIKE '%<gco:CharacterString>WGS 84 (EPSG:4326) WGS 84 (EPSG:4326)</gco:CharacterString>%';
UPDATE metadata SET data = replace(data, '<mrs:MD_ReferenceSystemTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ReferenceSystemTypeCode" codeListValue="geodeticGeographic2D geodeticGeographic2D"/>', '<mrs:MD_ReferenceSystemTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ReferenceSystemTypeCode" codeListValue="geodeticGeographic2D"/>') WHERE data LIKE '%<mrs:MD_ReferenceSystemTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ReferenceSystemTypeCode" codeListValue="geodeticGeographic2D geodeticGeographic2D"/>%';

UPDATE metadata SET data = replace(data, '<gcx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/31370 31370">EPSG:31370EPSG:31370</gcx:Anchor>', '<gcx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/31370">EPSG:31370</gcx:Anchor>') WHERE data LIKE '%<gcx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/31370 31370">EPSG:31370EPSG:31370</gcx:Anchor>%';
UPDATE metadata SET data = replace(data, '<gco:CharacterString>Belge 1972 / Belgian Lambert 72 (EPSG:31370) Belge 1972 / Belgian Lambert 72 (EPSG:31370)</gco:CharacterString>', '<gco:CharacterString>Belge 1972 / Belgian Lambert 72 (EPSG:31370)</gco:CharacterString>') WHERE data LIKE '%<gco:CharacterString>Belge 1972 / Belgian Lambert 72 (EPSG:31370) Belge 1972 / Belgian Lambert 72 (EPSG:31370)</gco:CharacterString>%';
UPDATE metadata SET data = replace(data, '<mrs:MD_ReferenceSystemTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ReferenceSystemTypeCode" codeListValue="projected projected"/>', '<mrs:MD_ReferenceSystemTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ReferenceSystemTypeCode" codeListValue="projected"/>') WHERE data LIKE '%<mrs:MD_ReferenceSystemTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ReferenceSystemTypeCode" codeListValue="projected projected"/>%';


